<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <CodeAnalysisRuleSet>..\..\Analyzers.ruleset</CodeAnalysisRuleSet>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>17bde2b4-986c-4211-9892-edcb7cf3d0f6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Template.WebApp.Host\Template.WebApp.Host.csproj" />
  </ItemGroup>

</Project>
